### ISSUE TITLE
ACL matching channel names or ID

### ISSUE THREAD

**Issue by gdelaney** [errbotio/err-backend-slackv3#61]
When using the channel name e.g: #channel in ACLS with allowrooms the command is blocked/rejected.
Should we be using the slack channel id or the name for ACLs?

**Comment by sijis** [comment]
Try the I'd of the channel.

**Comment by gdelaney** [comment]
If I compare the commit ids https://github.com/errbotio/err-backend-slackv3/pull/52 which works with the name to https://github.com/errbotio/err-backend-slackv3/issues/57  which is the ID where I noticed the change in behaviour. I am unable use ACLs on channel names or IDs

**Comment by nzlosh** [comment]
I'll take a look and see what's going on.
