### ISSUE TITLE
Multiple admins

### ISSUE THREAD

**Issue by torgeirl** [errbotio/err-backend-slackv3#63]
The README covers some changes to setting admins compared to the old Slack backend:

> **Bot Admins**
> Slack changed the way users are uniquely identified from display name @some_name to user id Uxxxxxx. Errbot configuration will need to be updated before administrators can be correctly identified aginst the ACL sets.
> 
> The UserID is in plain text format. It can be found in the the Slack full profile page or using the !whoami command (person field).

I'm able to set one admin with either `BOT_ADMINS = Uxxxxxxxx` or `BOT_ADMINS = (Uxxxxxxxx)` in `config.py`, but seem unable to set multiple admins. I've tested comma-separated with and without `'` and with and without parentheses.

The only docs mentioning how to set multiple admins are the [base Errbot docs](https://errbot.readthedocs.io/en/latest/user_guide/configuration/slack.html#bot-admins) with `BOT_ADMINS = ('@gbin', '@zoni')`, but I have tested `BOT_ADMINS = ('Uxxxxxxxx', 'Uxxxxxxxx')` without success.

**Comment by nzlosh** [comment]
Are you saying if `BOT_ADMINS` is set to a single entry ACL matching works and when there is more than one entry it stops working?

**Comment by torgeirl** [comment]
> Are you saying if `BOT_ADMINS` is set to a single entry ACL matching works and when there is more than one entry it stops working?

That is my experience, yes.

**Comment by nzlosh** [comment]
When configuring multiple admins, do you see any errors in the logs?

**Comment by torgeirl** [comment]
No warnings or error in logs. I started out with the latest released branch (`v0.1.1`), but switched to `main` to get the latests changes just in case (no difference).

My logs (removed timestamps for readability):
```
INFO     errbot.bootstrap          Found Storage plugin: Shelf.
INFO     errbot.bootstrap          Found Backend plugin: SlackV3
INFO     errbot.backends.slackv3   Verifying authentication token
INFO     errbot.backends.slackv3   Token accepted
INFO     errbot.backends.slackv3   Using RTM API.
INFO     errbot.backends.slackv3   Connecting to Slack RTM API
INFO     slack_sdk.rtm_v2          A new session has been established (session id: ****)
INFO     slack_sdk.rtm_v2          Starting to receive messages from a new connection (session id: ****)
INFO     errbot.core               Activate internal commands
INFO     errbot.plugin_manager     Activate bot plugins...
(...)
INFO     errbot.core               Notifying connection to all the plugins...
INFO     errbot.core               Plugin activation done.
```

The logs from lacking bot-admin privileges isn't very helpful, unfortunately:
```
INFO     errbot.plugins.ACLs       Matching ACL {} against username Uxxxxxx for command Health:restart.
INFO     errbot.core               Command None blocked or deferred.

VS

INFO     errbot.plugins.ACLs       Matching ACL {} against username U07GG4M18 for command Health:restart.
INFO     errbot.core               Processing command "restart" with parameters "" from <@Uxxxxxxxx>
INFO     slack_sdk.rtm_v2          The connection has been closed (session id: ****)
INFO     slack_sdk.rtm_v2          The connection has been closed (session id: ****)
INFO     errbot.plugin_manager     Shutdown.
INFO     errbot.plugin_manager     Bye.
INFO     errbot.bootstrap          Found Storage plugin: Shelf.
INFO     errbot.bootstrap          Found Backend plugin: SlackV3
```
(Not sure why «the connection has been closed» message echoes, but I assume that isn't relevant here.)

**Comment by torgeirl** [comment]
@nzlosh: can I help you any further with debugging this issue?

**Comment by nzlosh** [comment]
@torgeirl Sorry for the delay on this.  I'll try repoduce the error on my setup and get back to you this weekend.

**Comment by nzlosh** [comment]
I wasn't able to reproduce this issue on my setup.  If I have a single entry or multiple entries, the bot allows execution of admin commands.  I tested using the `!bot restart` command via direct message to the bot.

Single user - OK
```
BOT_ADMINS = "USOTO2SHO"
```

Multiple users in list form - OK
```
BOT_ADMINS = ["USOTO2SHO", "UAIF3AIRO", "UEPHAH6AH", "UTHABOH0K", "UEETHAITO6B", "UEIKEEB6OOP"]
```

Multiple users in tuple form - OK
```
BOT_ADMINS = ("USOTO2SHO", "UAIF3AIRO", "UEPHAH6AH", "UTHABOH0K", "UEETHAITO6B", "UEIKEEB6OOP")
```

Based on the logs you supplied, the `!bot restart` command was allowed which suggests the `BOT_ADMINS` is working on your setup too.

The only things I can think of as being a possible cause of ACL failure is an incorrect SlackID or possibly ACLs that include channel restrictions that are impacted by the bug https://github.com/errbotio/err-backend-slackv3/issues/61

**Comment by torgeirl** [comment]
@nzlosh: my issue was between my system environments (Kubernetes secrets) and the `config.py` file in my container, and predated the switch to the `backend-slackv3` backend. Sorry for not catching this myself, and thanks for taking the time to look into this! :pray:
