### ISSUE TITLE
slack RTM can send Slack Event like modals or messages with buttons?

### ISSUE THREAD

**Issue by johnclark84** [errbotio/err-backend-slackv3#69]
Hi everyone,

I'm working with errbot to have it running to send slack modals or messages with buttons to make same automation from the channels. But for now the only thing I make it, is have this connected to slack.RTM as classic app, but when I try to run some modal or message with buttons I only see the plain text but nothing as buttons or modal.
Can someone share me an example as how can I call a modal from slack.rtm?

If this is not posible from RTM, can some one share an example on how link nginx with errbot and left him listen to /slack/events? because I search it but I didn't find any useful example. I saw errbot is using flask but I don't understand how I can add a new target beside to create a webhook or I need to make a webhook for each slack event?

Thanks!

**Comment by nzlosh** [comment]
I've not personally attempted to use GUI elements in Slack so can't provide any direct experience for what you're attempting to do.  Although errbot doesn't provide direct support for GUI elements, it does allow access to the underlying SlackSDK module which should allow plugins to make calls to create GUI elements.  Documentation for SlackSDK is here https://slack.dev/python-slack-sdk/ the slack web api call is exposed through errbot's `self._bot.api_call()`.

**Comment by nzlosh** [comment]
As discussed in #70, errbot is not currently suited to building a slack app because these features are not portable across other backends supported by errbot.
