### ISSUE TITLE
errbot-backend-slackv3 module install via pip inaccessible without specifying BOT_EXTRA_BACKEND_DIR

### ISSUE THREAD

**Issue by p1co** [errbotio/err-backend-slackv3#91]
Without specifying BOT_EXTRA_BACKEND_DIR, errbot does not know about errbot-backend-slackv3 when it is installed via pip.

Specifying something like `BOT_EXTRA_BACKEND_DIR="/home/pico/err_test/lib/python3.10/site-packages"` seems a bit ugly and unnecessary. Why not make it so site-packages are checked?

> ~/err_test » pip show errbot-backend-slackv3                                                                                                                              
> Name: errbot-backend-slackv3
> Version: 0.2.1
> Summary: Errbot SlackV3 backend plugin
> Home-page: UNKNOWN
> Author: Errbot
> Author-email: 
> License: UNKNOWN
> Location: /home/pico/err_test/lib/python3.10/site-packages
> Requires: aiohttp, markdown, slack-sdk, slackeventsapi
> Required-by: 
> (err_test) ---------------------------------------------------------------------------------------------------------------------------------------------------------------
> ~/err_test » errbot                                                                                                                                                       
> 10:42:59 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
> Traceback (most recent call last):
>   File "/home/pico/err_test/bin/errbot", line 8, in <module>
>     sys.exit(main())
>   File "/home/pico/err_test/lib/python3.10/site-packages/errbot/cli.py", line 396, in main
>     bootstrap(backend, root_logger, config, restore)
>   File "/home/pico/err_test/lib/python3.10/site-packages/errbot/bootstrap.py", line 265, in bootstrap
>     bot = setup_bot(bot_class, logger, config, restore)
>   File "/home/pico/err_test/lib/python3.10/site-packages/errbot/bootstrap.py", line 172, in setup_bot
>     backendpm = BackendPluginManager(
>   File "/home/pico/err_test/lib/python3.10/site-packages/errbot/backend_plugin_manager.py", line 53, in __init__
>     raise PluginNotFoundException(
> errbot.backend_plugin_manager.PluginNotFoundException: Could not find the plugin named SlackV3 in ['/home/pico/err_test/lib/python3.10/site-packages/errbot/backends'].
> (err_test) ---------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by nzlosh** [comment]
A [fix](https://github.com/errbotio/errbot/commit/edb20826a7a1839f3c8c81e42a9c4bb4d4a527d7) was pushed to errbot master branch that should address this issue.
