### ISSUE TITLE
SlackV3 plugin fails to load alert but appears to be working since bot can actually connect to Slack

### ISSUE THREAD

**Issue by lanthos** [errbotio/err-backend-slackv3#92]
Hello,

I'm getting the following error from the bot (as a DM in slack) after it's loaded up:

`Did not find any plugin in /Users/lanthos/repos/robo2/bot/backend/err-backend-slackv3/build/lib/slackv3.Error: SlackV3 failed to activate: 'NoneType' object has no attribute 'is_activated'.`

I've tried digging around to see if I could figure out what the problem is but haven't been able to figure it out.   The part of the code that is throwing this error is the `activate_non_started_plugins` method in plugin_manager.py from errbot (I'm running the latest from pip, 6.1.9), specifically line 444.  And I've got `errbot-backend-slackv3        0.2.1` installed for the backend.

I've setup things as per the read me:

created backend folder in same folder as config.py and plugins folder
inside backend folder I did `git clone https://github.com/errbotio/err-backend-slackv3`
I cded into the `err-backend-slackv3` folder and ran `pip install .`  (side note, the docs forget to mention you have to go into the directory with setup.py to actually run `pip install .` or it won't work)
I've added the slackv3 backend and extra backend directory as per the directions.

Inside the directory `/Users/lanthos/repos/robo2/bot/backend/err-backend-slackv3/build/lib/slackv3` I can see the plugin and everything appears to be there.

The thing that is weird, is if I don't use the `BACKEND="SlackV3"` declaration the bot can't even connect to Slack at all.  But if I use it I can connect but I get this error.  The bot appears to be working normally, my other plugins work just fine, I just keep getting this error about SlackV3.  Any ideas on what could be the problem?  

Any help would be greatly appreciated, thank you!

**Comment by lanthos** [comment]
Figured out what the problem was.  

`BOT_EXTRA_PLUGIN_DIR = '/opt/app/robo2/bot/'` worked previously but with using the backend as an extra plugin you need to add `plugins` to the end of your extra plugin dir or it will cause problems.

**Comment by nzlosh** [comment]
Sorry for not seeing this issue sooner.  Your fix seems a little odd, but if the bot is working, it may be acceptable to leave like this.

There are three types of plugin specialisations in errbot.  The *plugin*, *backend* and *store*.  Slackv3 is a backend, which means the `BOT_EXTRA_BACKEND_DIR` would be the correct configuration variable to use to point to the slackv3 installation location.

**Comment by lanthos** [comment]
My setting for that was `BOT_EXTRA_BACKEND_DIR = "/Users/lanthos/repos/robo2/bot/backend"`.  I don't know how many folders down the plugins would look for things or if it looks for a specific folder called plugins but based upon the fact that the backend actually loaded and the error was plugin related, I'm guessing it just checks all folders inside of the path you specify for plugins.  And since I only ever had the one before it was never a problem. :D  But things have been running fine now since I made that change.
