### ISSUE TITLE
Using org level tokens

### ISSUE THREAD

**Issue by gdelaney** [errbotio/err-backend-slackv3#96]
When using the backend with a Org level scope token, the creation and population of the user cache expects all users to have a team_id field in the profile. Users (mostly bot) that use a Org level bot token do not have a team_id and the bot fails to start up.

I have raised a pr #95  but I am unsure if thats the correct way, as a user at the org level has a list of teams. Should we query the api for all the teams (workspaces) a user is a member of or just use the enterprise_id of the org user as the team to fetch the domain?

**Comment by nzlosh** [comment]
https://github.com/errbotio/err-backend-slackv3/pull/95 has been merged.  Thank you for the contribution @gdelaney
